plugins {
    id("com.gradleup.shadow")
    alias(libs.plugins.publish)
}

architectury {
    platformSetupLoomIde()
    fabric()
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

loom.mixin.useLegacyMixinAp = true

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation("${libs.fabric.loader.get()}")
    modImplementation("${libs.fabric.api.get()}")

    // Fabric dependencies go here
    //modImplementation("maven.modrinth:millies-core-libs:${rootProject.property("corelibs")}-Fabric")
    //modImplementation("dev.architectury:architectury-fabric:${libs.versions.arch.api.get()}")

    modImplementation("com.terraformersmc:modmenu:${rootProject.property("mod_menu")}")

    // Fabric Loader has MixinExtras built-in since 0.15.0 but not MixinSquared
    //include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${libs.versions.mixinextras.get()}")))
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${libs.versions.mixinsquared.get()}")))

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    filesMatching('fabric.mod.json') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "fabric_loader_version": libs.versions.fabric.loader.get(),
                "fabric_api_version": libs.versions.fabric.api.get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_fabric"),
                "architectury_api": libs.versions.arch.api.get()
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

publishMods {
    file = remapJar.archiveFile
    modLoaders.add("fabric")
    // STABLE, BETA, ALPHA
    type = STABLE

    modrinth {
        projectId = "abcdefg"
        accessToken = property("modrinth_token")
        minecraftVersions.add("1.20.1")
        enviroment = CLIENT_AND_SERVER
        requires("fabric-api")

        def changelogFile = rootProject.file(".Changelogs/${rootProject.property("mod_version")}-Changelog.md")
        changelog = changelogFile.exists() ? changelogFile.getText("UTF-8") : ""
    }
}
