# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = examplemod
mod_name = Example Mod
mod_version = 1.0.0
mod_description = Example 26.1+ multiloader mod
mod_license = MIT
mod_authors = Lumynity Studios

maven_group = net.lumynity
archives_base_name = ExampleMod

minecraft_version_constraint_forge = [26.1,)
minecraft_version_constraint_fabric = ~26.1
supported_versions = 26.1,26.1.1,26.1.2

# Dependencies
lumynlib = 1.0.0+mc26.1
terrablender = 26.1.2.0.1
mod_menu = 18.0.0-alpha.8