# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Loom Properties
arch_loom = 1.13-SNAPSHOT
arch_plugin = 3.4-SNAPSHOT
shadow = 8.3.6

# Mod Properties
mod_id = examplemod
mod_name = Example Mod
mod_version = 1.0.0
mod_description = Example 26.1+ multiloader mod
mod_license = MIT
mod_authors = Lumynity Studios

maven_group = net.lumynity
archives_base_name = ExampleMod
enabled_platforms = fabric,forge

minecraft_version_constraint_forge = [1.20.1]
minecraft_version_constraint_fabric = 1.20.1

# Minecraft Properties
minecraft = 1.20.1
fabric_loader = 0.17.1
forge = 47.4.5
parchment = 2023.09.03

# Dependencies
lumynlib = 1.0.0+mc1.20.1
architectury_api = 9.2.14
fabric_api = 0.92.7+1.20.1
modmenu = 7.2.2