# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = examplemod
mod_name = Example Mod
mod_version = 1.0.0
mod_description = Example 26.1.2 multiloader mod for Lumynity Studios' projects
mod_license = MIT
mod_authors = Lumynity Studios

archives_base_name = ExampleMod

minecraft_version_constraint_forge = [26.1.2]
minecraft_version_constraint_fabric = 26.1.2
supported_versions = 26.1.2

# Dependencies
corelibs = 1.0.0
mod_menu = 18.0.0-alpha.8