plugins {
    id('com.gradleup.shadow')
}

architectury {
    platformSetupLoomIde()
    loader('quilt')
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentQuilt.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}
// Exclude Fabric Loader from configuration so there's no duplicate mod errors
configurations.configureEach {
    exclude group: 'net.fabricmc', module: 'fabric-loader'
}

repositories {
    maven { url 'https://maven.quiltmc.org/repository/release/' }
}

dependencies {
    modImplementation("${libs.quilt.loader.get()}")
    modImplementation("${libs.quilt.api.get()}")

    // Quilt dependencies go here
    //modImplementation("dev.architectury:architectury-fabric:${libs.versions.arch.api.get()}")
    //modImplementation("com.github.glitchfiend:TerraBlender-fabric:${libs.versions.minecraft.get()}-${rootProject.property("terrablender")}")

    modImplementation("com.terraformersmc:modmenu:${rootProject.property("mod_menu")}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    // Quilt Loader has MixinExtras built-in since 0.16.0-beta.1 but not MixinSquared
    //include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${libs.versions.mixinextras.get()}")))
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${libs.versions.mixinsquared.get()}")))

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionQuilt')
}

processResources {
    inputs.property 'group', project.group
    inputs.property 'version', project.version

    filesMatching('quilt.mod.json') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "group": rootProject.property("maven_group"),
                "quilt_loader_version": libs.versions.quilt.loader.get(),
                "quilt_api_version": libs.versions.quilt.api.get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_fabric")
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
