plugins {
    id("com.gradleup.shadow")
}

/* Uncomment if you want datagen
def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}
 */

loom {
    forge {
        mixinConfig "${rootProject.property("mod_id")}.mixins.json",
                "${rootProject.property("mod_id")}-forge.mixins.json"
    }


    runs {
        /* Uncomment if you want datagen
        data {
            data()
            programArgs "--all", "--mod", "${rootProject.property("mod_id")}"
            programArgs "--output", generatedResources.absolutePath
        }
         */
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge("net.minecraftforge:forge:${libs.versions.minecraft.get()}-${libs.versions.forge.get()}")
    modImplementation("net.minecraftforge:forge:${libs.versions.minecraft.get()}-${libs.versions.forge.get()}")

    // Forge dependencies go here
    //modImplementation("maven.modrinth:lumynlib:${rootProject.property("lumynlib")}-Forge")
    //modImplementation("dev.architectury:architectury:${libs.versions.arch.api.get()}")
    //modImplementation("com.github.glitchfiend:TerraBlender-forge:${libs.versions.minecraft.get()}-${rootProject.property("terrablender")}")

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "forge_version": libs.versions.forge.get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_forge")
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
