
/*
                                                          TODO: FIX AND FINISH NEOFORGE
Sources:
https://github.com/Flandre923/neoForge1.20.1-Tutorialmod-code/tree/master
https://generate.architectury.dev/ (downloaded NeoForge 1.20.4 template)
*/


plugins {
    id("com.gradleup.shadow")
}

/* Uncomment if you want datagen
def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}
 */

loom {
    runs {
        /* Uncomment if you want datagen
        data {
            data()
            programArgs "--all", "--mod", "${rootProject.property("mod_id")}"
            programArgs "--output", generatedResources.absolutePath
        }
         */
    }
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:forge:${libs.versions.minecraft.get()}-${libs.versions.neoforge.get()}"

    // NeoForge dependencies go here
    //yes here

    // NeoForge only mainlines MixinExtras since 1.21.1
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${libs.versions.mixinextras.get()}"))
    modImplementation(include("io.github.llamalad7:mixinextras-neoforge:${libs.versions.mixinextras.get()}"))
    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${libs.versions.mixinsquared.get()}"))
    modImplementation(include("com.github.bawnorton.mixinsquared:mixinsquared-neoforge:${libs.versions.mixinsquared.get()}"))

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "forge_version": libs.versions.forge.get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_forge")
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
